### PR TITLE
Stumble speed almost perfectly matches 1.52.

### PR DESCRIPTION
**Pull request by Raptor007**

### CODE REVIEW

**Comment by dynamic0** [comment]
Hello man. I've tried to contact you for couple of weeks now.  I'm just asking could you send your gamex86.dll-file with TNG and BOT features? I've been doing a project for AQ2 for a year now, which you can check it out on aq2-tng.com.
The package would be little more awesome, if it would have that.

Thanks,
dynamic

**Comment by Raptor007** [comment]
You found me!  I wish GitHub had user-to-user messaging.  In future, the best way to get in touch with me is a private message on QuakeNet IRC channel AQ2World, which you can access here: http://webchat.quakenet.org/?channels=aq2world

I'll get you my gamex86.dll in a few hours when I get home.  (Eventually I'll bump the version number to 2.82 and put a release onto the GitHub page, but there are still a few more bugs to fix first.)

**Comment by Raptor007** [comment]
Here is the current build: http://www.raptor007.com/action-quake2/action/gamex86.dll

Or you can build it yourself by installing MinGW, then open it and type this:
`git clone https://github.com/aq2-tng/aq2-tng.git
cd aq2-tng/source
git checkout bots
make`

**Comment by dynamic0** [comment]
Big thanks man! Wasn't expecting a reply anymore. As you can see, I've had
problems trying to contact you, but oh well.


I've seen you being active on the GitHub and I'm happily surprised you're
still doing stuff for AQ2. I guess you're the only one...


By the way, what else are you going to do for AQ2?
If you have some ideas for AQ2 please tell me, I'm very interested!


Again big thanks for the file!

- dynamic


2017-02-14 8:24 GMT+02:00 Raptor007 <notifications@github.com>:

**Comment by Raptor007** [comment]
I have a list of bugs and feature ideas here: https://github.com/Raptor007/aq2-tng/issues

Anything significantly game-changing is going to have a cvar to control it so people can still play classic style, since this game is very nostalgic for many of us.

I think I'm the only active coder for AQ2 at the moment, but last year Maniac did a lot of work on `sv_fps` support (which is now merged into master).  There's also a small but active community of server admins and players on QuakeNet IRC, but our timezones and schedules vary so you might have to leave a message and stay logged in overnight to get a reply.

**Pull request merged**
