### PR TITLE
Fixed multiplayer view models in 'bots' branch.

### PR DESCRIPTION
**Pull request by Raptor007**
The 'bots' branch had a nasty bug that severely broke multiplayer (with q2proded64 at least): some players would be invisible to others, and sometimes you'd see a ghost image of your own 3rd person model on top of your position.  The root cause was having grenadewait in player_state_t instead of edict_t.  I also brought over the latest changes from the 'master' branch and cleaned up anything that gcc -Wall warned about.  Along the way, I also made a couple of tweaks to special/unique item pickup so people couldn't horde things they can't actually utilize.

### CODE REVIEW

**Comment by hifi** [comment]
Thanks for the pull request.

There's a small problem in the bots branch that it can't be merged back to master ever, because the license is unclear.

I could merge this but there's not much going to happen except that unfortunately.

**Comment by Raptor007** [comment]
Ah, that's unfortunate, but I guess it makes sense; it's probably hard to track down who you'd even ask for permission at this point.  Even so, it would be nice to pull commit 8900605 into your bots branch so the multiplayer view models aren't broken.  Other than that, I can stick to my own fork.

And thank you for providing the AQ2 source repository!  Even though I can tell a lot of different hands have touched it over the years, most of it is surprisingly easy to follow.

**Comment by hifi** [comment]
If you're interested in AQ2 development further, I could move this to an organization and give you access. Looks like you're doing a lot of generic fixes as well that are not bot specific.

The only thing I would hope is that the master branch doesn't see basic gameplay changes for regular teamplay.

**Comment by Raptor007** [comment]
Sure!  Or I could just commit the non-bot-related changes to my fork of the 'master' branch and submit occasional pull requests on that branch; whichever works better for you.  Either way I'd like to keep using bots on my server, so I should probably get familiar with GitHub's merging so I can keep both branches up-to-date.

I've been having fun with the code, but I also don't want to change the gameplay.  The biggest change that I made prevents players from picking up 2 of the same weapon or special item regardless of how many total they're allowed to carry (which is how I *think* I remember it being a long time ago) but I can add a server cvar to toggle that restriction.

**Pull request merged**
